# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @export
eigenMapMatMult <- function(A, B) {
    .Call(`_Sincast_eigenMapMatMult`, A, B)
}

